import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import GlitchBackground from "../components/GlitchBackground";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased`}
    >
      <body className="min-h-screen flex flex-col relative">
        <GlitchBackground />
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
